default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: admin_emails_on_sign_up

test:
  <<: *default
  database: admin_emails_on_sign_up_test

production:
  <<: *default
  database: admin_emails_on_sign_up_pro
